"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Product = { id: number; kode: string; nama: string; harga: number };
type Variant = { id: number; color: string; size: string };
type Form = { color: string; size: string };
const emptyForm: Form = { color: "", size: "" };
const variantSku = (product: Product, form: Form) => `${product.kode}-${form.color.trim().replaceAll(" ", "-")}-${form.size.trim().replaceAll(" ", "-")}`.toUpperCase();

export default function VariantModal({ product, onClose }: { product: Product; onClose: () => void }) {
  const [variants, setVariants] = useState<Variant[]>([]); const [form, setForm] = useState<Form>(emptyForm); const [editingId, setEditingId] = useState<number | null>(null); const [saving, setSaving] = useState(false);
  async function loadVariants() { const { data, error } = await supabase.from("product_variants").select("id,color,size").eq("product_id", product.id).order("created_at"); if (error) alert(`Gagal memuat varian: ${error.message}`); else setVariants((data ?? []) as Variant[]); }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void loadVariants(); }, []);
  function reset() { setForm(emptyForm); setEditingId(null); }
  async function save() { if (!form.color.trim() || !form.size.trim()) return alert("Warna dan ukuran wajib diisi."); setSaving(true); const payload = { color: form.color.trim(), size: form.size.trim(), sku: variantSku(product, form) }; const { error } = editingId ? await supabase.from("product_variants").update(payload).eq("id", editingId) : await supabase.from("product_variants").insert({ product_id: product.id, ...payload, price: product.harga, stock: 0 }); setSaving(false); if (error) return alert(`Gagal menyimpan varian: ${error.message}`); reset(); void loadVariants(); }
  function edit(variant: Variant) { setEditingId(variant.id); setForm({ color: variant.color, size: variant.size }); }
  async function deleteVariant(variant: Variant) { if (variants.length <= 1) return alert("Produk harus memiliki minimal satu varian. Ubah varian ini bila diperlukan."); if (!confirm(`Hapus varian ${variant.color} / ${variant.size}?`)) return; const { error } = await supabase.from("product_variants").delete().eq("id", variant.id); if (error) return alert(`Gagal menghapus varian: ${error.message}`); void loadVariants(); }
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 text-gray-900 shadow-xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">Kelola Variasi</h2><p className="mt-1 text-sm text-gray-500">{product.nama} · Atur warna dan ukuran. SKU serta harga mengikuti data produk.</p></div><button onClick={onClose} className="rounded-lg bg-gray-100 px-3 py-2 text-sm font-medium hover:bg-gray-200">Tutup</button></div><div className="mt-6 rounded-xl border border-pink-100 bg-pink-50 p-4"><p className="mb-3 text-sm font-bold text-pink-900">{editingId ? "Ubah variasi" : "Tambah variasi"}</p><div className="grid gap-3 sm:grid-cols-3"><Field value={form.color} onChange={(value) => setForm((current) => ({ ...current, color: value }))} placeholder="Warna" /><Field value={form.size} onChange={(value) => setForm((current) => ({ ...current, size: value }))} placeholder="Ukuran" /><div className="flex gap-2"><button disabled={saving} onClick={() => void save()} className="flex-1 rounded-lg bg-pink-600 px-4 py-2 font-semibold text-white hover:bg-pink-700 disabled:bg-pink-300">{saving ? "Menyimpan..." : editingId ? "Simpan" : "Tambah"}</button>{editingId && <button onClick={reset} className="rounded-lg bg-white px-3 py-2 font-semibold text-gray-700 ring-1 ring-gray-200">Batal</button>}</div></div></div><div className="mt-6 overflow-x-auto rounded-xl border border-gray-200"><table className="w-full min-w-[480px] text-sm"><thead className="bg-pink-600 text-left text-xs uppercase tracking-wide text-white"><tr><th className="px-4 py-3">Warna</th><th className="px-4 py-3">Ukuran</th><th className="px-4 py-3 text-right">Aksi</th></tr></thead><tbody>{variants.map((variant) => <tr key={variant.id} className="border-t border-gray-100"><td className="px-4 py-3 font-medium">{variant.color}</td><td className="px-4 py-3">{variant.size}</td><td className="px-4 py-3 text-right"><button onClick={() => edit(variant)} className="mr-3 font-semibold text-pink-700 hover:text-pink-800">Ubah</button><button onClick={() => void deleteVariant(variant)} className="font-semibold text-red-600 hover:text-red-700">Hapus</button></td></tr>)}{variants.length === 0 && <tr><td colSpan={3} className="px-4 py-10 text-center text-gray-500">Belum ada variasi.</td></tr>}</tbody></table></div></div></div>;
}
function Field({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="rounded-lg border border-pink-200 bg-white px-3 py-2 text-gray-900 outline-none focus:border-pink-500 focus:ring-2 focus:ring-pink-100" />; }
