"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { useBrand } from "@/components/brand/BrandProvider";

type Product = { id: number; nama: string };
type CustomPrice = { id: number; nama: string; harga: number };
const emptyForm = { nama: "", harga: "" };
const formatRupiah = (value: number) => `Rp ${value.toLocaleString("id-ID")}`;

export default function VariantModal({ product, onClose }: { product: Product; onClose: () => void }) {
  const { brand } = useBrand();
  const [prices, setPrices] = useState<CustomPrice[]>([]); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState<number | null>(null); const [saving, setSaving] = useState(false);
  async function loadPrices() { const { data, error } = await supabase.from("product_custom_prices").select("id,nama,harga").eq("brand_id", brand?.id ?? "").eq("product_id", product.id).order("created_at"); if (error) alert(`Gagal memuat harga: ${error.message}`); else setPrices((data ?? []) as CustomPrice[]); }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void loadPrices(); }, []);
  function reset() { setForm(emptyForm); setEditingId(null); }
  async function save() { if (!form.nama.trim() || !form.harga || Number(form.harga) < 0) return alert("Nama harga dan nominal harga wajib diisi."); setSaving(true); const payload = { nama: form.nama.trim(), harga: Number(form.harga) }; const { error } = editingId ? await supabase.from("product_custom_prices").update(payload).eq("id", editingId).eq("brand_id", brand?.id ?? "") : await supabase.from("product_custom_prices").insert({ product_id: product.id, brand_id: brand?.id, ...payload }); setSaving(false); if (error) return alert(`Gagal menyimpan harga: ${error.message}`); reset(); void loadPrices(); }
  function edit(price: CustomPrice) { setEditingId(price.id); setForm({ nama: price.nama, harga: String(price.harga) }); }
  async function deletePrice(price: CustomPrice) { if (!confirm(`Hapus harga ${price.nama}?`)) return; const { error } = await supabase.from("product_custom_prices").delete().eq("id", price.id).eq("brand_id", brand?.id ?? ""); if (error) return alert(`Gagal menghapus harga: ${error.message}`); void loadPrices(); }
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 text-gray-900 shadow-xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">Custom Harga</h2><p className="mt-1 text-sm text-gray-500">{product.nama} · Tambahkan harga untuk kebutuhan seperti distributor atau reseller.</p></div><button onClick={onClose} className="rounded-lg bg-gray-100 px-3 py-2 text-sm font-medium hover:bg-gray-200">Tutup</button></div><div className="mt-6 rounded-xl border border-pink-100 bg-pink-50 p-4"><p className="mb-3 text-sm font-bold text-pink-900">{editingId ? "Ubah harga" : "Tambah harga"}</p><div className="grid gap-3 sm:grid-cols-3"><input value={form.nama} onChange={(event) => setForm((current) => ({ ...current, nama: event.target.value }))} placeholder="Nama harga" className="rounded-lg border border-pink-200 bg-white px-3 py-2" /><input value={form.harga} onChange={(event) => setForm((current) => ({ ...current, harga: event.target.value.replace(/\D/g, "") }))} inputMode="numeric" placeholder="Harga" className="rounded-lg border border-pink-200 bg-white px-3 py-2" /><div className="flex gap-2"><button disabled={saving} onClick={() => void save()} className="flex-1 rounded-lg bg-pink-600 px-4 py-2 font-semibold text-white disabled:bg-pink-300">{saving ? "Menyimpan..." : editingId ? "Simpan" : "Tambah"}</button>{editingId && <button onClick={reset} className="rounded-lg bg-white px-3 py-2 font-semibold text-gray-700 ring-1 ring-gray-200">Batal</button>}</div></div></div><div className="mt-6 overflow-x-auto rounded-xl border border-gray-200"><table className="w-full min-w-[480px] text-sm"><thead className="bg-pink-600 text-left text-xs uppercase tracking-wide text-white"><tr><th className="px-4 py-3">Nama harga</th><th className="px-4 py-3">Harga</th><th className="px-4 py-3 text-right">Aksi</th></tr></thead><tbody>{prices.map((price) => <tr key={price.id} className="border-t border-gray-100"><td className="px-4 py-3 font-medium">{price.nama}</td><td className="px-4 py-3">{formatRupiah(Number(price.harga))}</td><td className="px-4 py-3 text-right"><button onClick={() => edit(price)} className="mr-3 font-semibold text-pink-700">Ubah</button><button onClick={() => void deletePrice(price)} className="font-semibold text-red-600">Hapus</button></td></tr>)}{prices.length === 0 && <tr><td colSpan={3} className="px-4 py-10 text-center text-gray-500">Belum ada custom harga.</td></tr>}</tbody></table></div></div></div>;
}
