alter table public.transactions add column if not exists discount_amount numeric(14,2) not null default 0;
alter table public.transactions add column if not exists discount_reason text;

-- Gunakan total diskon yang telah dihitung POS; fungsi ini menjaga agar tidak melebihi subtotal.
create or replace function public.create_sale(p_items jsonb, p_payment_method text, p_paid_amount numeric, p_notes text default null, p_customer_name text default null, p_discount_amount numeric default 0, p_discount_reason text default null)
returns table (transaction_id bigint, invoice_number text, total numeric, change_amount numeric)
language plpgsql security definer set search_path=public as $$
declare v_item jsonb; v_variant public.product_variants%rowtype; v_product public.products%rowtype; v_id bigint; v_qty int; v_subtotal numeric:=0; v_discount numeric; v_total numeric; v_paid numeric; v_change numeric; v_tx bigint; v_invoice text;
begin
 if coalesce(public.current_user_role() not in ('OWNER','ADMIN','KASIR'),true) then raise exception 'Anda tidak memiliki akses'; end if;
 if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'Keranjang tidak boleh kosong'; end if;
 if p_payment_method not in ('CASH','QRIS','DEBIT','PIUTANG') then raise exception 'Metode pembayaran tidak valid'; end if; if p_payment_method='PIUTANG' and nullif(trim(coalesce(p_customer_name,'')),'') is null then raise exception 'Nama pelanggan wajib untuk piutang'; end if;
 for v_item in select value from jsonb_array_elements(p_items) loop v_id:=(v_item->>'variant_id')::bigint; v_qty:=(v_item->>'quantity')::int; select * into v_variant from public.product_variants where id=v_id for update; if not found or v_qty is null or v_qty<=0 or v_variant.stock<v_qty then raise exception 'Item atau stok tidak valid'; end if; v_subtotal:=v_subtotal+v_variant.price*v_qty; end loop;
 v_discount:=greatest(coalesce(p_discount_amount,0),0); if v_discount>v_subtotal then raise exception 'Diskon melebihi subtotal'; end if; v_total:=v_subtotal-v_discount; v_paid:=greatest(coalesce(p_paid_amount,0),0); if p_payment_method<>'PIUTANG' and v_paid<v_total then raise exception 'Nominal pembayaran kurang'; end if; v_change:=case when p_payment_method='PIUTANG' then 0 else v_paid-v_total end; v_invoice:='TRX-'||to_char(now(),'YYYYMMDD')||'-'||lpad(nextval('public.transaction_invoice_seq')::text,6,'0');
 insert into public.transactions(invoice_number,subtotal,total,discount_amount,discount_reason,paid_amount,change_amount,payment_method,payment_status,customer_name,notes,cashier_id) values(v_invoice,v_subtotal,v_total,v_discount,nullif(trim(p_discount_reason),''),v_paid,v_change,p_payment_method,case when v_paid>=v_total then 'LUNAS' else 'BELUM_LUNAS' end,nullif(trim(p_customer_name),''),nullif(trim(p_notes),''),auth.uid()) returning id into v_tx; if v_paid>0 then insert into public.transaction_payments(transaction_id,amount,payment_method,notes,received_by) values(v_tx,v_paid,case when p_payment_method='PIUTANG' then 'CASH' else p_payment_method end,'Pembayaran awal',auth.uid()); end if;
 for v_item in select value from jsonb_array_elements(p_items) loop v_id:=(v_item->>'variant_id')::bigint; v_qty:=(v_item->>'quantity')::int; select * into v_variant from public.product_variants where id=v_id; select * into v_product from public.products where id=v_variant.product_id; insert into public.transaction_items(transaction_id,product_id,product_variant_id,product_name,variant_name,quantity,unit_price,subtotal) values(v_tx,v_product.id,v_id,v_product.nama,concat(v_variant.color,' / ',v_variant.size),v_qty,v_variant.price,v_variant.price*v_qty); update public.product_variants set stock=stock-v_qty where id=v_id; insert into public.stock_movements(product_id,product_variant_id,tipe,jumlah,keterangan) values(v_product.id,v_id,'KELUAR',v_qty,'Penjualan '||v_invoice); end loop;
 return query select v_tx,v_invoice,v_total,v_change;
end; $$;
revoke all on function public.create_sale(jsonb,text,numeric,text,text,numeric,text) from public,anon;
grant execute on function public.create_sale(jsonb,text,numeric,text,text,numeric,text) to authenticated;
