-- Retur per item transaksi. Transaksi asal tidak dihapus agar audit penjualan tetap utuh.
create table if not exists public.transaction_returns (
  id bigint generated by default as identity primary key,
  transaction_item_id bigint not null references public.transaction_items(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  refund_amount numeric(14, 2) not null check (refund_amount >= 0),
  refund_method text not null check (refund_method in ('CASH', 'QRIS', 'DEBIT')),
  reason text,
  returned_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists transaction_returns_item_idx on public.transaction_returns (transaction_item_id, created_at desc);

alter table public.transaction_returns enable row level security;
drop policy if exists "Read allowed transaction returns" on public.transaction_returns;
create policy "Read allowed transaction returns" on public.transaction_returns for select to authenticated using (
  exists (
    select 1 from public.transaction_items i join public.transactions t on t.id = i.transaction_id
    where i.id = transaction_item_id and (t.cashier_id = auth.uid() or public.current_user_role() in ('OWNER', 'ADMIN'))
  )
);

create or replace function public.return_transaction_item(
  p_transaction_item_id bigint,
  p_quantity integer,
  p_refund_method text,
  p_reason text default null
)
returns table (return_id bigint, refund_amount numeric, remaining_quantity integer)
language plpgsql security definer set search_path = public
as $$
declare
  v_item public.transaction_items%rowtype;
  v_transaction public.transactions%rowtype;
  v_returned_quantity integer;
  v_refund_amount numeric(14, 2);
  v_return_id bigint;
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'Jumlah retur harus lebih dari 0'; end if;
  if p_refund_method not in ('CASH', 'QRIS', 'DEBIT') then raise exception 'Metode pengembalian dana tidak valid'; end if;
  perform pg_advisory_xact_lock(p_transaction_item_id);
  select * into v_item from public.transaction_items where id = p_transaction_item_id for update;
  if not found then raise exception 'Item transaksi tidak ditemukan'; end if;
  select * into v_transaction from public.transactions where id = v_item.transaction_id;
  if v_transaction.cashier_id <> auth.uid() and coalesce(public.current_user_role() not in ('OWNER', 'ADMIN'), true) then raise exception 'Anda tidak memiliki akses untuk melakukan retur ini'; end if;
  if v_item.product_variant_id is null then raise exception 'Item transaksi lama tidak memiliki data varian dan tidak dapat diretur otomatis'; end if;
  select coalesce(sum(quantity), 0) into v_returned_quantity from public.transaction_returns where transaction_item_id = v_item.id;
  if p_quantity > v_item.quantity - v_returned_quantity then raise exception 'Jumlah retur melebihi sisa item yang dapat diretur'; end if;
  v_refund_amount := v_item.unit_price * p_quantity;
  insert into public.transaction_returns (transaction_item_id, quantity, refund_amount, refund_method, reason, returned_by)
  values (v_item.id, p_quantity, v_refund_amount, p_refund_method, nullif(trim(p_reason), ''), auth.uid()) returning id into v_return_id;
  update public.product_variants set stock = stock + p_quantity where id = v_item.product_variant_id;
  insert into public.stock_movements (product_id, product_variant_id, tipe, jumlah, keterangan)
  values (v_item.product_id, v_item.product_variant_id, 'RETUR', p_quantity, 'Retur ' || v_transaction.invoice_number || ': ' || coalesce(nullif(trim(p_reason), ''), 'tanpa catatan'));
  return query select v_return_id, v_refund_amount, v_item.quantity - v_returned_quantity - p_quantity;
end;
$$;

revoke all on function public.return_transaction_item(bigint, integer, text, text) from public, anon;
grant execute on function public.return_transaction_item(bigint, integer, text, text) to authenticated;
