-- Piutang, pelunasan, dan koreksi informasi struk untuk POS varian.
alter table public.transactions add column if not exists customer_name text;
alter table public.transactions add column if not exists payment_status text not null default 'LUNAS';

alter table public.transactions drop constraint if exists transactions_payment_method_check;
alter table public.transactions add constraint transactions_payment_method_check
  check (payment_method in ('CASH', 'QRIS', 'DEBIT', 'PIUTANG'));
alter table public.transactions drop constraint if exists transactions_payment_status_check;
alter table public.transactions add constraint transactions_payment_status_check
  check (payment_status in ('LUNAS', 'BELUM_LUNAS'));

create table if not exists public.transaction_payments (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references public.transactions(id) on delete cascade,
  amount numeric(14, 2) not null check (amount > 0),
  payment_method text not null check (payment_method in ('CASH', 'QRIS', 'DEBIT')),
  notes text,
  received_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists transaction_payments_transaction_id_idx on public.transaction_payments (transaction_id, created_at desc);
alter table public.transaction_payments enable row level security;
drop policy if exists "Read transaction payments" on public.transaction_payments;
create policy "Read transaction payments" on public.transaction_payments for select to authenticated using (
  exists (select 1 from public.transactions t where t.id = transaction_id and (t.cashier_id = auth.uid() or public.current_user_role() in ('OWNER', 'ADMIN')))
);

create or replace function public.create_sale(p_items jsonb, p_payment_method text, p_paid_amount numeric, p_notes text default null, p_customer_name text default null)
returns table (transaction_id bigint, invoice_number text, total numeric, change_amount numeric)
language plpgsql security definer set search_path = public
as $$
declare
  v_item jsonb; v_product public.products%rowtype; v_variant public.product_variants%rowtype;
  v_variant_id bigint; v_quantity integer; v_subtotal numeric(14,2) := 0; v_total numeric(14,2);
  v_paid_amount numeric(14,2); v_change_amount numeric(14,2); v_transaction_id bigint; v_invoice_number text;
begin
  if coalesce(public.current_user_role() not in ('OWNER', 'ADMIN', 'KASIR'), true) then raise exception 'Anda tidak memiliki akses untuk membuat transaksi'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'Keranjang tidak boleh kosong'; end if;
  if p_payment_method not in ('CASH', 'QRIS', 'DEBIT', 'PIUTANG') then raise exception 'Metode pembayaran tidak valid'; end if;
  if p_payment_method = 'PIUTANG' and nullif(trim(coalesce(p_customer_name, '')), '') is null then raise exception 'Nama pelanggan wajib untuk transaksi piutang'; end if;
  for v_item in select value from jsonb_array_elements(p_items) loop
    v_variant_id := (v_item ->> 'variant_id')::bigint; v_quantity := (v_item ->> 'quantity')::integer;
    if v_variant_id is null or v_quantity is null or v_quantity <= 0 then raise exception 'Varian transaksi tidak valid'; end if;
    select * into v_variant from public.product_variants where id = v_variant_id for update;
    if not found then raise exception 'Varian tidak ditemukan'; end if;
    if v_variant.stock < v_quantity then raise exception 'Stok varian % / % tidak mencukupi', v_variant.color, v_variant.size; end if;
    v_subtotal := v_subtotal + v_variant.price * v_quantity;
  end loop;
  v_total := v_subtotal; v_paid_amount := greatest(coalesce(p_paid_amount, 0), 0);
  if p_payment_method <> 'PIUTANG' and v_paid_amount < v_total then raise exception 'Nominal pembayaran kurang'; end if;
  if p_payment_method = 'PIUTANG' and v_paid_amount > v_total then raise exception 'Uang muka tidak boleh melebihi total'; end if;
  v_change_amount := case when p_payment_method = 'PIUTANG' then 0 else v_paid_amount - v_total end;
  v_invoice_number := 'TRX-' || to_char(now(), 'YYYYMMDD') || '-' || lpad(nextval('public.transaction_invoice_seq')::text, 6, '0');
  insert into public.transactions (invoice_number, subtotal, total, paid_amount, change_amount, payment_method, payment_status, customer_name, notes, cashier_id)
  values (v_invoice_number, v_subtotal, v_total, v_paid_amount, v_change_amount, p_payment_method, case when v_paid_amount >= v_total then 'LUNAS' else 'BELUM_LUNAS' end, nullif(trim(p_customer_name), ''), nullif(trim(p_notes), ''), auth.uid()) returning id into v_transaction_id;
  if v_paid_amount > 0 then insert into public.transaction_payments (transaction_id, amount, payment_method, notes, received_by) values (v_transaction_id, v_paid_amount, case when p_payment_method = 'PIUTANG' then 'CASH' else p_payment_method end, 'Pembayaran awal', auth.uid()); end if;
  for v_item in select value from jsonb_array_elements(p_items) loop
    v_variant_id := (v_item ->> 'variant_id')::bigint; v_quantity := (v_item ->> 'quantity')::integer;
    select * into v_variant from public.product_variants where id = v_variant_id;
    select * into v_product from public.products where id = v_variant.product_id;
    insert into public.transaction_items (transaction_id, product_id, product_variant_id, product_name, variant_name, quantity, unit_price, subtotal)
    values (v_transaction_id, v_product.id, v_variant.id, v_product.nama, concat(v_variant.color, ' / ', v_variant.size), v_quantity, v_variant.price, v_variant.price * v_quantity);
    update public.product_variants set stock = stock - v_quantity where id = v_variant.id;
    insert into public.stock_movements (product_id, product_variant_id, tipe, jumlah, keterangan) values (v_product.id, v_variant.id, 'KELUAR', v_quantity, 'Penjualan ' || v_invoice_number);
  end loop;
  return query select v_transaction_id, v_invoice_number, v_total, v_change_amount;
end;
$$;

create or replace function public.complete_receivable(p_transaction_id bigint, p_amount numeric, p_payment_method text, p_notes text default null)
returns table (paid_amount numeric, remaining_amount numeric, payment_status text)
language plpgsql security definer set search_path = public
as $$
declare v_transaction public.transactions%rowtype; v_remaining numeric(14,2); v_amount numeric(14,2); v_new_paid numeric(14,2);
begin
  select * into v_transaction from public.transactions where id = p_transaction_id for update;
  if not found then raise exception 'Transaksi tidak ditemukan'; end if;
  if v_transaction.cashier_id <> auth.uid() and coalesce(public.current_user_role() not in ('OWNER', 'ADMIN'), true) then raise exception 'Anda tidak memiliki akses'; end if;
  if v_transaction.payment_status = 'LUNAS' then raise exception 'Transaksi ini sudah lunas'; end if;
  if p_payment_method not in ('CASH', 'QRIS', 'DEBIT') then raise exception 'Metode pembayaran tidak valid'; end if;
  v_remaining := v_transaction.total - v_transaction.paid_amount; v_amount := coalesce(p_amount, 0);
  if v_amount <= 0 or v_amount > v_remaining then raise exception 'Nominal pelunasan harus lebih dari 0 dan maksimal %', v_remaining; end if;
  v_new_paid := v_transaction.paid_amount + v_amount;
  update public.transactions set paid_amount = v_new_paid, payment_status = case when v_new_paid >= total then 'LUNAS' else 'BELUM_LUNAS' end where id = p_transaction_id;
  insert into public.transaction_payments (transaction_id, amount, payment_method, notes, received_by) values (p_transaction_id, v_amount, p_payment_method, nullif(trim(p_notes), ''), auth.uid());
  return query select v_new_paid, v_transaction.total - v_new_paid, case when v_new_paid >= v_transaction.total then 'LUNAS' else 'BELUM_LUNAS' end;
end;
$$;

create or replace function public.update_receipt(p_transaction_id bigint, p_customer_name text, p_notes text)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if not exists (select 1 from public.transactions t where t.id = p_transaction_id and (t.cashier_id = auth.uid() or public.current_user_role() in ('OWNER', 'ADMIN'))) then raise exception 'Anda tidak memiliki akses'; end if;
  update public.transactions set customer_name = nullif(trim(p_customer_name), ''), notes = nullif(trim(p_notes), '') where id = p_transaction_id;
end;
$$;

revoke all on function public.create_sale(jsonb, text, numeric, text, text) from public, anon;
grant execute on function public.create_sale(jsonb, text, numeric, text, text) to authenticated;
grant execute on function public.complete_receivable(bigint, numeric, text, text) to authenticated;
grant execute on function public.update_receipt(bigint, text, text) to authenticated;
