-- Product stock is now managed once per product. Variants stay only as legacy
-- transaction history; new inventory and sales records do not use them.
create table if not exists public.product_custom_prices (
  id bigint generated by default as identity primary key,
  brand_id uuid not null references public.brands(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  nama text not null check (length(trim(nama)) > 0),
  harga numeric(14,2) not null check (harga >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, nama)
);
create index if not exists product_custom_prices_brand_product_idx on public.product_custom_prices (brand_id, product_id);
alter table public.product_custom_prices enable row level security;
create policy "Brand isolation" on public.product_custom_prices for all to authenticated using (public.can_access_brand(brand_id)) with check (public.can_access_brand(brand_id));

-- Do not let legacy variant triggers overwrite product-level stock.
drop trigger if exists on_product_variant_stock_change on public.product_variants;
drop trigger if exists on_product_created_create_default_variant on public.products;

create or replace function public.adjust_product_stock(p_brand_id uuid, p_product_id bigint, p_type text, p_quantity integer, p_notes text default null)
returns table (product_id bigint, stock integer) language plpgsql security definer set search_path=public as $$
declare v_product public.products%rowtype; v_change integer;
begin
  perform public.assert_brand_access(p_brand_id);
  if coalesce(public.current_user_role(),'') not in ('OWNER','ADMIN') then raise exception 'Anda tidak memiliki akses untuk mengubah stok'; end if;
  if p_type not in ('MASUK','KELUAR','RETUR') or p_quantity is null or p_quantity <= 0 then raise exception 'Data pergerakan stok tidak valid'; end if;
  select * into v_product from public.products where id=p_product_id and brand_id=p_brand_id for update;
  if not found then raise exception 'Produk tidak ditemukan untuk brand aktif'; end if;
  v_change := case when p_type='KELUAR' then -p_quantity else p_quantity end;
  if v_product.stok + v_change < 0 then raise exception 'Stok produk tidak mencukupi'; end if;
  update public.products set stok=stok+v_change where id=v_product.id;
  insert into public.stock_movements(brand_id,product_id,product_variant_id,tipe,jumlah,keterangan) values(p_brand_id,v_product.id,null,p_type,p_quantity,nullif(trim(p_notes),''));
  return query select v_product.id, v_product.stok + v_change;
end $$;

create or replace function public.set_product_total_stock(p_brand_id uuid, p_product_id bigint, p_stock integer)
returns table (product_id bigint, stock integer) language plpgsql security definer set search_path=public as $$
declare v_product public.products%rowtype; v_difference integer;
begin
  perform public.assert_brand_access(p_brand_id);
  if coalesce(public.current_user_role(),'') not in ('OWNER','ADMIN') then raise exception 'Anda tidak memiliki akses untuk mengubah stok'; end if;
  if p_stock is null or p_stock < 0 then raise exception 'Stok tidak boleh negatif'; end if;
  select * into v_product from public.products where id=p_product_id and brand_id=p_brand_id for update;
  if not found then raise exception 'Produk tidak ditemukan untuk brand aktif'; end if;
  v_difference := p_stock-v_product.stok;
  update public.products set stok=p_stock where id=v_product.id;
  if v_difference <> 0 then insert into public.stock_movements(brand_id,product_id,product_variant_id,tipe,jumlah,keterangan) values(p_brand_id,v_product.id,null,case when v_difference>0 then 'MASUK' else 'KELUAR' end,abs(v_difference),'Penyesuaian stok total produk'); end if;
  return query select v_product.id,p_stock;
end $$;

-- Product-level sales may optionally use a named custom price.
create or replace function public.create_sale(p_brand_id uuid, p_items jsonb, p_payment_method text, p_paid_amount numeric, p_notes text default null, p_customer_name text default null, p_discount_amount numeric default 0, p_discount_reason text default null, p_created_at timestamptz default null)
returns table (transaction_id bigint, invoice_number text, total numeric, change_amount numeric) language plpgsql security definer set search_path=public as $$
declare i jsonb; p public.products%rowtype; cp public.product_custom_prices%rowtype; product_id_value bigint; quantity_value integer; price_value numeric; price_name text; sub numeric:=0; disc numeric; tot numeric; paid numeric; ch numeric; tx bigint; inv text; created_value timestamptz;
begin
  perform public.assert_brand_access(p_brand_id);
  if coalesce(public.current_user_role() not in ('OWNER','ADMIN','KASIR'),true) then raise exception 'Anda tidak memiliki akses'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Keranjang tidak boleh kosong'; end if;
  if p_payment_method not in ('CASH','QRIS','TRANSFER','PIUTANG') then raise exception 'Metode pembayaran tidak valid'; end if;
  for i in select value from jsonb_array_elements(p_items) loop
    product_id_value := (i->>'product_id')::bigint; quantity_value := (i->>'quantity')::integer;
    select * into p from public.products where id=product_id_value and brand_id=p_brand_id for update;
    if not found or quantity_value is null or quantity_value<=0 or p.stok<quantity_value then raise exception 'Item atau stok tidak valid'; end if;
    price_value:=p.harga; price_name:='Harga utama';
    if nullif(i->>'custom_price_id','') is not null then select * into cp from public.product_custom_prices where id=(i->>'custom_price_id')::bigint and product_id=p.id and brand_id=p_brand_id; if not found then raise exception 'Custom harga tidak ditemukan'; end if; price_value:=cp.harga; price_name:=cp.nama; end if;
    sub:=sub+price_value*quantity_value;
  end loop;
  disc:=greatest(coalesce(p_discount_amount,0),0); if disc>sub then raise exception 'Diskon melebihi subtotal'; end if; tot:=sub-disc; paid:=greatest(coalesce(p_paid_amount,0),0); if p_payment_method<>'PIUTANG' and paid<tot then raise exception 'Nominal pembayaran kurang'; end if;
  ch:=case when p_payment_method='PIUTANG' then 0 else paid-tot end; created_value:=coalesce(p_created_at,now()); inv:='TRX-'||to_char(created_value,'YYYYMMDD')||'-'||lpad(nextval('public.transaction_invoice_seq')::text,6,'0');
  insert into public.transactions(brand_id,invoice_number,subtotal,total,discount_amount,discount_reason,paid_amount,change_amount,payment_method,payment_status,customer_name,notes,cashier_id,created_at) values(p_brand_id,inv,sub,tot,disc,nullif(trim(p_discount_reason),''),paid,ch,p_payment_method,case when paid>=tot then 'LUNAS' else 'BELUM_LUNAS' end,nullif(trim(p_customer_name),''),nullif(trim(p_notes),''),auth.uid(),created_value) returning id into tx;
  if paid>0 then insert into public.transaction_payments(brand_id,transaction_id,amount,payment_method,notes,received_by) values(p_brand_id,tx,paid,case when p_payment_method='PIUTANG' then 'CASH' else p_payment_method end,'Pembayaran awal',auth.uid()); end if;
  for i in select value from jsonb_array_elements(p_items) loop
    product_id_value := (i->>'product_id')::bigint; quantity_value := (i->>'quantity')::integer; select * into p from public.products where id=product_id_value; price_value:=p.harga; price_name:='Harga utama';
    if nullif(i->>'custom_price_id','') is not null then select * into cp from public.product_custom_prices where id=(i->>'custom_price_id')::bigint; price_value:=cp.harga; price_name:=cp.nama; end if;
    insert into public.transaction_items(brand_id,transaction_id,product_id,product_variant_id,product_name,variant_name,quantity,unit_price,subtotal) values(p_brand_id,tx,p.id,null,p.nama,price_name,quantity_value,price_value,price_value*quantity_value);
    update public.products set stok=stok-quantity_value where id=p.id;
    insert into public.stock_movements(brand_id,product_id,product_variant_id,tipe,jumlah,keterangan) values(p_brand_id,p.id,null,'KELUAR',quantity_value,'Penjualan '||inv);
  end loop;
  return query select tx,inv,tot,ch;
end $$;

revoke all on function public.adjust_product_stock(uuid,bigint,text,integer,text), public.set_product_total_stock(uuid,bigint,integer), public.create_sale(uuid,jsonb,text,numeric,text,text,numeric,text,timestamptz) from public, anon;
grant execute on function public.adjust_product_stock(uuid,bigint,text,integer,text), public.set_product_total_stock(uuid,bigint,integer), public.create_sale(uuid,jsonb,text,numeric,text,text,numeric,text,timestamptz) to authenticated;
