-- SPRINT 4 tahap 1: varian produk fashion dan stok per varian.
create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  sku text not null unique,
  color text not null default 'Default',
  size text not null default 'One Size',
  price numeric(14, 2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, color, size)
);

-- Setiap produk lama memperoleh satu varian awal agar data lama tetap utuh.
insert into public.product_variants (product_id, sku, color, size, price, stock)
select id, kode, 'Default', 'One Size', harga, stok
from public.products
on conflict (product_id, color, size) do nothing;

-- Kolom ini disiapkan untuk tahap POS dan riwayat transaksi per varian.
alter table public.stock_movements add column if not exists product_variant_id bigint references public.product_variants(id) on delete restrict;
alter table public.transaction_items add column if not exists product_variant_id bigint references public.product_variants(id) on delete restrict;
alter table public.transaction_items add column if not exists variant_name text;

update public.transaction_items items
set product_variant_id = variants.id,
    variant_name = concat(variants.color, ' / ', variants.size)
from public.product_variants variants
where variants.product_id = items.product_id
  and items.product_variant_id is null;

-- Stok total produk lama selalu mengikuti total seluruh variannya.
create or replace function public.sync_product_stock_from_variants()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_product_id bigint;
begin
  v_product_id := coalesce(new.product_id, old.product_id);
  update public.products
  set stok = coalesce((select sum(stock) from public.product_variants where product_id = v_product_id), 0)
  where id = v_product_id;
  return coalesce(new, old);
end;
$$;

drop trigger if exists on_product_variant_stock_change on public.product_variants;
create trigger on_product_variant_stock_change
after insert or update or delete on public.product_variants
for each row execute procedure public.sync_product_stock_from_variants();

-- Produk baru otomatis memiliki varian awal, lalu dapat diubah menjadi ukuran/warna spesifik.
create or replace function public.create_default_product_variant()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.product_variants (product_id, sku, color, size, price, stock)
  values (new.id, new.kode, 'Default', 'One Size', new.harga, new.stok)
  on conflict (product_id, color, size) do nothing;
  return new;
end;
$$;

drop trigger if exists on_product_created_create_default_variant on public.products;
create trigger on_product_created_create_default_variant
after insert on public.products
for each row execute procedure public.create_default_product_variant();

alter table public.product_variants enable row level security;
drop policy if exists "Authenticated read variants" on public.product_variants;
create policy "Authenticated read variants" on public.product_variants
for select to authenticated using (true);
drop policy if exists "Owner admin manage variants" on public.product_variants;
create policy "Owner admin manage variants" on public.product_variants
for all to authenticated
using (public.current_user_role() in ('OWNER', 'ADMIN'))
with check (public.current_user_role() in ('OWNER', 'ADMIN'));

-- POS versi varian: satu transaksi mengunci dan mengurangi stok varian yang dipilih.
create or replace function public.create_sale(p_items jsonb, p_payment_method text, p_paid_amount numeric, p_notes text default null)
returns table (transaction_id bigint, invoice_number text, total numeric, change_amount numeric)
language plpgsql security definer set search_path = public
as $$
declare
  v_item jsonb; v_product public.products%rowtype; v_variant public.product_variants%rowtype;
  v_variant_id bigint; v_quantity integer; v_subtotal numeric(14, 2) := 0;
  v_total numeric(14, 2); v_paid_amount numeric(14, 2); v_change_amount numeric(14, 2);
  v_transaction_id bigint; v_invoice_number text;
begin
  if coalesce(public.current_user_role() not in ('OWNER', 'ADMIN', 'KASIR'), true) then raise exception 'Anda tidak memiliki akses untuk membuat transaksi'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'Keranjang tidak boleh kosong'; end if;
  if p_payment_method not in ('CASH', 'QRIS', 'DEBIT') then raise exception 'Metode pembayaran tidak valid'; end if;
  for v_item in select value from jsonb_array_elements(p_items) loop
    v_variant_id := (v_item ->> 'variant_id')::bigint; v_quantity := (v_item ->> 'quantity')::integer;
    if v_variant_id is null or v_quantity is null or v_quantity <= 0 then raise exception 'Varian transaksi tidak valid'; end if;
    select * into v_variant from public.product_variants where id = v_variant_id for update;
    if not found then raise exception 'Varian dengan ID % tidak ditemukan', v_variant_id; end if;
    if v_variant.stock < v_quantity then raise exception 'Stok varian % / % tidak mencukupi', v_variant.color, v_variant.size; end if;
    v_subtotal := v_subtotal + (v_variant.price * v_quantity);
  end loop;
  v_total := v_subtotal; v_paid_amount := coalesce(p_paid_amount, v_total);
  if v_paid_amount < v_total then raise exception 'Nominal pembayaran kurang'; end if;
  v_change_amount := v_paid_amount - v_total;
  v_invoice_number := 'TRX-' || to_char(now(), 'YYYYMMDD') || '-' || lpad(nextval('public.transaction_invoice_seq')::text, 6, '0');
  insert into public.transactions (invoice_number, subtotal, total, paid_amount, change_amount, payment_method, notes, cashier_id)
  values (v_invoice_number, v_subtotal, v_total, v_paid_amount, v_change_amount, p_payment_method, nullif(trim(p_notes), ''), auth.uid()) returning id into v_transaction_id;
  for v_item in select value from jsonb_array_elements(p_items) loop
    v_variant_id := (v_item ->> 'variant_id')::bigint; v_quantity := (v_item ->> 'quantity')::integer;
    select * into v_variant from public.product_variants where id = v_variant_id;
    select * into v_product from public.products where id = v_variant.product_id;
    insert into public.transaction_items (transaction_id, product_id, product_variant_id, product_name, variant_name, quantity, unit_price, subtotal)
    values (v_transaction_id, v_product.id, v_variant.id, v_product.nama, concat(v_variant.color, ' / ', v_variant.size), v_quantity, v_variant.price, v_variant.price * v_quantity);
    update public.product_variants set stock = stock - v_quantity where id = v_variant.id;
    insert into public.stock_movements (product_id, product_variant_id, tipe, jumlah, keterangan)
    values (v_product.id, v_variant.id, 'KELUAR', v_quantity, 'Penjualan ' || v_invoice_number);
  end loop;
  return query select v_transaction_id, v_invoice_number, v_total, v_change_amount;
end;
$$;
