-- SPRINT 2: POS / Kasir. Jalankan seluruh file ini sekali di Supabase SQL Editor.
create sequence if not exists public.transaction_invoice_seq;

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  subtotal numeric(14, 2) not null default 0 check (subtotal >= 0),
  total numeric(14, 2) not null default 0 check (total >= 0),
  paid_amount numeric(14, 2) not null default 0 check (paid_amount >= 0),
  change_amount numeric(14, 2) not null default 0 check (change_amount >= 0),
  payment_method text not null default 'CASH' check (payment_method in ('CASH', 'QRIS', 'DEBIT')),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references public.transactions(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(14, 2) not null check (unit_price >= 0),
  subtotal numeric(14, 2) not null check (subtotal >= 0),
  created_at timestamptz not null default now()
);

create index if not exists transactions_created_at_idx on public.transactions (created_at desc);
create index if not exists transaction_items_transaction_id_idx on public.transaction_items (transaction_id);
create index if not exists transaction_items_product_id_idx on public.transaction_items (product_id);

-- Penyimpanan transaksi, item, dan stok berjalan dalam satu transaksi database.
create or replace function public.create_sale(p_items jsonb, p_payment_method text, p_paid_amount numeric, p_notes text default null)
returns table (transaction_id bigint, invoice_number text, total numeric, change_amount numeric)
language plpgsql security definer set search_path = public
as $$
declare
  v_item jsonb; v_product public.products%rowtype; v_product_id bigint; v_quantity integer;
  v_subtotal numeric(14, 2) := 0; v_total numeric(14, 2); v_paid_amount numeric(14, 2);
  v_change_amount numeric(14, 2); v_transaction_id bigint; v_invoice_number text;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'Keranjang tidak boleh kosong'; end if;
  if p_payment_method not in ('CASH', 'QRIS', 'DEBIT') then raise exception 'Metode pembayaran tidak valid'; end if;
  for v_item in select value from jsonb_array_elements(p_items) loop
    v_product_id := (v_item ->> 'product_id')::bigint; v_quantity := (v_item ->> 'quantity')::integer;
    if v_product_id is null or v_quantity is null or v_quantity <= 0 then raise exception 'Item transaksi tidak valid'; end if;
    select * into v_product from public.products where id = v_product_id for update;
    if not found then raise exception 'Produk dengan ID % tidak ditemukan', v_product_id; end if;
    if v_product.stok < v_quantity then raise exception 'Stok % tidak mencukupi', v_product.nama; end if;
    v_subtotal := v_subtotal + (v_product.harga * v_quantity);
  end loop;
  v_total := v_subtotal; v_paid_amount := coalesce(p_paid_amount, v_total);
  if v_paid_amount < v_total then raise exception 'Nominal pembayaran kurang'; end if;
  v_change_amount := v_paid_amount - v_total;
  v_invoice_number := 'TRX-' || to_char(now(), 'YYYYMMDD') || '-' || lpad(nextval('public.transaction_invoice_seq')::text, 6, '0');
  insert into public.transactions (invoice_number, subtotal, total, paid_amount, change_amount, payment_method, notes)
  values (v_invoice_number, v_subtotal, v_total, v_paid_amount, v_change_amount, p_payment_method, nullif(trim(p_notes), '')) returning id into v_transaction_id;
  for v_item in select value from jsonb_array_elements(p_items) loop
    v_product_id := (v_item ->> 'product_id')::bigint; v_quantity := (v_item ->> 'quantity')::integer;
    select * into v_product from public.products where id = v_product_id;
    insert into public.transaction_items (transaction_id, product_id, product_name, quantity, unit_price, subtotal)
    values (v_transaction_id, v_product.id, v_product.nama, v_quantity, v_product.harga, v_product.harga * v_quantity);
    update public.products set stok = stok - v_quantity where id = v_product.id;
    insert into public.stock_movements (product_id, tipe, jumlah, keterangan)
    values (v_product.id, 'KELUAR', v_quantity, 'Penjualan ' || v_invoice_number);
  end loop;
  return query select v_transaction_id, v_invoice_number, v_total, v_change_amount;
end;
$$;

-- RLS: data hanya dibaca aplikasi; transaksi baru wajib lewat RPC atomik di atas.
alter table public.transactions enable row level security;
alter table public.transaction_items enable row level security;
drop policy if exists "Read transactions from app" on public.transactions;
create policy "Read transactions from app" on public.transactions for select to anon, authenticated using (true);
drop policy if exists "Read transaction items from app" on public.transaction_items;
create policy "Read transaction items from app" on public.transaction_items for select to anon, authenticated using (true);
grant execute on function public.create_sale(jsonb, text, numeric, text) to anon, authenticated;
